apiVersion: v1
kind: Pod
metadata:
  name: client-not-watching
spec:
  containers:
    - name: client
      image: gcr.io/grpc-testing/wanlin/server:1033
      args:
        - -c
        - |
          sleep 2h
      command:
      - bash
    - name: envoy
      image: gcr.io/grpc-testing/wanlin/envoy-test:1711
    - name: xdsserver
      image: gcr.io/grpc-testing/wanlin/example-server:go-control-plane-original
      args:
        - -c
        - |
          sleep 2h
      command:
      - bash
  
  
  
  
  